const fs=require('fs'),path=require('path');
const base=path.resolve(__dirname,'../android'),dir=path.join(base,'app/src/main/java/ir/hesabketab/app');
fs.mkdirSync(dir,{recursive:true});
const receiver=String.raw`package ir.hesabketab.app;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.Build;import android.provider.Telephony;import android.telephony.SmsMessage;import androidx.core.app.NotificationCompat;import org.json.*;
public class BankSmsReceiver extends BroadcastReceiver{
 static final String PREFS="bank_sms_bridge",QUEUE="pending_queue",DONE="confirmed_queue",CHANNEL="bank_sms";
 public void onReceive(Context c,Intent in){if(!Telephony.Sms.Intents.SMS_RECEIVED_ACTION.equals(in.getAction())||c.checkSelfPermission(Manifest.permission.RECEIVE_SMS)!=PackageManager.PERMISSION_GRANTED)return;SmsMessage[] ms=Telephony.Sms.Intents.getMessagesFromIntent(in);if(ms==null||ms.length==0)return;StringBuilder b=new StringBuilder();for(SmsMessage m:ms)if(m!=null)b.append(m.getMessageBody());String text=b.toString().trim();if(!text.matches("(?s).*\\\\d[\\\\d,٬،. ]{2,}.*")||!(text.contains("واریز")||text.contains("برداشت")||text.contains("خرید")||text.contains("پرداخت")||text.contains("انتقال")||text.contains("بانک")||text.contains("موجودی")))return;try{SharedPreferences p=c.getSharedPreferences(PREFS,0);JSONArray q=new JSONArray(p.getString(QUEUE,"[]"));long now=System.currentTimeMillis();for(int x=0;x<q.length();x++){JSONObject o=q.getJSONObject(x);if(text.equals(o.optString("text"))&&now-o.optLong("receivedAt")<60000)return;}String id=now+"-"+Integer.toHexString(text.hashCode());int nid=("sms-"+id).hashCode()&0x7fffffff;JSONObject o=new JSONObject();o.put("id",id);o.put("text",text);o.put("receivedAt",now);o.put("notificationId",nid);q.put(o);p.edit().putString(QUEUE,q.toString()).apply();notify(c,text,id,nid);}catch(Exception e){}}
 static void notify(Context c,String text,String id,int nid){if(Build.VERSION.SDK_INT>=33&&c.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)return;NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(CHANNEL,"تراکنش‌های بانکی",NotificationManager.IMPORTANCE_HIGH));Intent i=new Intent(c,SmsEntryActivity.class).putExtra("id",id).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent pi=PendingIntent.getActivity(c,nid,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);nm.notify(nid,new NotificationCompat.Builder(c,CHANNEL).setSmallIcon(c.getApplicationInfo().icon).setContentTitle("تراکنش بانکی جدید").setContentText("برای ثبت تراکنش لمس کنید").setStyle(new NotificationCompat.BigTextStyle().bigText(text)).setPriority(NotificationCompat.PRIORITY_HIGH).setAutoCancel(true).setOnlyAlertOnce(true).setContentIntent(pi).build());}
}`;
const plugin=String.raw`package ir.hesabketab.app;
import android.Manifest;import android.content.*;import com.getcapacitor.*;import com.getcapacitor.annotation.*;import org.json.*;
@CapacitorPlugin(name="BankSms",permissions={@Permission(strings={Manifest.permission.RECEIVE_SMS},alias="sms")}) public class BankSmsPlugin extends Plugin{SharedPreferences p(){return getContext().getSharedPreferences(BankSmsReceiver.PREFS,0);}@PluginMethod public void requestPermission(PluginCall c){if(getPermissionState("sms")==PermissionState.GRANTED){c.resolve(new JSObject().put("granted",true));return;}requestPermissionForAlias("sms",c,"ok");}@PermissionCallback private void ok(PluginCall c){c.resolve(new JSObject().put("granted",getPermissionState("sms")==PermissionState.GRANTED));}@PluginMethod public void getPendingSms(PluginCall c){get(c,BankSmsReceiver.QUEUE);}@PluginMethod public void getConfirmedSms(PluginCall c){get(c,BankSmsReceiver.DONE);}void get(PluginCall c,String k){try{JSONArray q=new JSONArray(p().getString(k,"[]"));if(q.length()==0){c.resolve(new JSObject().put("has",false));return;}JSONObject o=q.getJSONObject(0);JSObject r=new JSObject();for(java.util.Iterator<String> it=o.keys();it.hasNext();){String n=it.next();r.put(n,o.opt(n));}r.put("has",true);c.resolve(r);}catch(Exception e){c.reject("queue",e);}}@PluginMethod public void markHandled(PluginCall c){drop(c,BankSmsReceiver.QUEUE);}@PluginMethod public void markConfirmedHandled(PluginCall c){drop(c,BankSmsReceiver.DONE);}void drop(PluginCall c,String k){try{JSONArray q=new JSONArray(p().getString(k,"[]")),n=new JSONArray();for(int i=1;i<q.length();i++)n.put(q.get(i));p().edit().putString(k,n.toString()).apply();c.resolve();}catch(Exception e){c.reject("queue",e);}}}`;
const activity=String.raw`package ir.hesabketab.app;
import android.app.*;import android.content.*;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import org.json.*;
public class SmsEntryActivity extends Activity{JSONObject src;EditText amount,bank,day,desc;RadioGroup type;int d(float n){return(int)(n*getResources().getDisplayMetrics().density);}EditText f(String h,int t){EditText e=new EditText(this);e.setHint(h);e.setInputType(t);e.setTextDirection(View.TEXT_DIRECTION_RTL);return e;}public void onCreate(Bundle b){super.onCreate(b);src=find(getIntent().getStringExtra("id"));if(src==null){finish();return;}ScrollView s=new ScrollView(this);LinearLayout l=new LinearLayout(this);l.setPadding(d(20),d(16),d(20),d(20));l.setOrientation(LinearLayout.VERTICAL);s.addView(l);TextView title=new TextView(this);title.setText("ثبت تراکنش بانکی");title.setTextSize(22);title.setGravity(Gravity.RIGHT);l.addView(title);TextView raw=new TextView(this);raw.setText(src.optString("text"));raw.setGravity(Gravity.RIGHT);raw.setPadding(0,d(12),0,d(12));l.addView(raw);type=new RadioGroup(this);RadioButton out=new RadioButton(this);out.setText("برداشت");out.setId(1);RadioButton in=new RadioButton(this);in.setText("واریز");in.setId(2);type.addView(out);type.addView(in);type.check(src.optString("text").contains("واریز")?2:1);l.addView(type);amount=f("مبلغ (تومان)",InputType.TYPE_CLASS_NUMBER);l.addView(amount);bank=f("نام بانک",InputType.TYPE_CLASS_TEXT);l.addView(bank);day=f("روز ماه",InputType.TYPE_CLASS_NUMBER);l.addView(day);desc=f("شرح",InputType.TYPE_CLASS_TEXT);l.addView(desc);Button save=new Button(this);save.setText("ثبت");l.addView(save);save.setOnClickListener(v->save());setContentView(s);}JSONObject find(String id){try{JSONArray q=new JSONArray(getSharedPreferences(BankSmsReceiver.PREFS,0).getString(BankSmsReceiver.QUEUE,"[]"));for(int i=0;i<q.length();i++)if(id.equals(q.getJSONObject(i).optString("id")))return q.getJSONObject(i);}catch(Exception e){}return null;}void save(){String a=amount.getText().toString().replaceAll("[^0-9]","");if(a.isEmpty()){Toast.makeText(this,"مبلغ را وارد کنید",0).show();return;}try{JSONObject x=new JSONObject();x.put("type",type.getCheckedRadioButtonId()==2?"income":"expense");x.put("amount",a);x.put("bank",bank.getText().toString());x.put("day",day.getText().toString());x.put("desc",desc.getText().toString());SharedPreferences p=getSharedPreferences(BankSmsReceiver.PREFS,0);JSONArray q=new JSONArray(p.getString(BankSmsReceiver.QUEUE,"[]")),rest=new JSONArray(),done=new JSONArray(p.getString(BankSmsReceiver.DONE,"[]"));for(int i=0;i<q.length();i++)if(!src.optString("id").equals(q.getJSONObject(i).optString("id")))rest.put(q.get(i));done.put(x);p.edit().putString(BankSmsReceiver.QUEUE,rest.toString()).putString(BankSmsReceiver.DONE,done.toString()).apply();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).cancel(src.optInt("notificationId"));finish();}catch(Exception e){Toast.makeText(this,"ثبت انجام نشد",0).show();}}}`;
const main=String.raw`package ir.hesabketab.app;import android.Manifest;import android.os.*;import android.content.pm.PackageManager;import com.getcapacitor.BridgeActivity;public class MainActivity extends BridgeActivity{public void onCreate(Bundle b){registerPlugin(BankSmsPlugin.class);super.onCreate(b);if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECEIVE_SMS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECEIVE_SMS},4201);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},4202);}}`;
fs.writeFileSync(path.join(dir,'BankSmsReceiver.java'),receiver);fs.writeFileSync(path.join(dir,'BankSmsPlugin.java'),plugin);fs.writeFileSync(path.join(dir,'SmsEntryActivity.java'),activity);fs.writeFileSync(path.join(dir,'MainActivity.java'),main);
const m=path.join(base,'app/src/main/AndroidManifest.xml');if(fs.existsSync(m)){let s=fs.readFileSync(m,'utf8');if(!s.includes('RECEIVE_SMS'))s=s.replace(/(<manifest\b[^>]*>)/,'$1\n<uses-permission android:name="android.permission.RECEIVE_SMS"/><uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>');if(!s.includes('SmsEntryActivity'))s=s.replace('</application>','<activity android:name=".SmsEntryActivity" android:exported="false"/><receiver android:name=".BankSmsReceiver" android:exported="true" android:permission="android.permission.BROADCAST_SMS"><intent-filter><action android:name="android.provider.Telephony.SMS_RECEIVED"/></intent-filter></receiver></application>');fs.writeFileSync(m,s);}
const g=path.join(base,'app/build.gradle');if(fs.existsSync(g)){let s=fs.readFileSync(g,'utf8');if(!s.includes('androidx.core:core'))s=s.replace(/dependencies\s*\{/,'dependencies {\nimplementation "androidx.core:core:1.15.0"');fs.writeFileSync(g,s);}
